---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CodeService
  labels:
    app: CodeService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CodeService
  template:
    metadata:
      labels:
        app: CodeService
    spec:
      containers:
        - name: CodeService
          image: username/CodeService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MetalOrderService
  labels:
    app: MetalOrderService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MetalOrderService
  template:
    metadata:
      labels:
        app: MetalOrderService
    spec:
      containers:
        - name: MetalOrderService
          image: username/MetalOrderService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MoldService
  labels:
    app: MoldService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MoldService
  template:
    metadata:
      labels:
        app: MoldService
    spec:
      containers:
        - name: MoldService
          image: username/MoldService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: CodeService
  labels:
    app: CodeService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CodeService


---


apiVersion: v1
kind: Service
metadata:
  name: MetalOrderService
  labels:
    app: MetalOrderService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MetalOrderService


---


apiVersion: v1
kind: Service
metadata:
  name: MoldService
  labels:
    app: MoldService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MoldService

